/** @type {import('tailwindcss').Config} */
import PrimeUI from 'tailwindcss-primeui';
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {
      colors: {
        'color-verde-header':'rgb(0, 113, 61)',
        'color-verde-portal':'rgb(7, 101, 58)',
        'color-verde-postular':'rgb(132, 190, 24)',
        'color-verde-hover':'rgb(12, 177, 101)',
        'color-verde-oscuro':'rgb(0, 113, 61)',
        'color-verde-claro':'rgb(52, 168, 83)',
        "secondary-fixed": "#d9e6da",
        "outline-variant": "#becabb",
        "on-tertiary-fixed": "#002203",
        "on-tertiary-container": "#b4fcab",
        "tertiary": "#1b5e20",
        "primary-container": "#007a33",
        "surface-container-highest": "#e0e3e5",
        "error-container": "#ffdad6",
        "outline": "#6f7a6d",
        "on-background": "#191c1e",
        "surface-dim": "#d8dadc",
        "secondary": "#556158",
        "on-secondary-container": "#5b675e",
        "secondary-container": "#d9e6da",
        "primary": "#005e26",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "inverse-surface": "#2d3133",
        "on-primary": "#ffffff",
        "surface-bright": "#f7f9fb",
        "on-secondary-fixed": "#131e17",
        "on-primary-fixed-variant": "#005320",
        "surface": "#f7f9fb",
        "primary-fixed": "#93f9a2",
        "on-tertiary-fixed-variant": "#0c5216",
        "on-surface": "#191c1e",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#acf4a4",
        "on-primary-container": "#a1ffad",
        "surface-tint": "#006e2d",
        "on-primary-fixed": "#002109",
        "surface-container-high": "#e6e8ea",
        "surface-variant": "#e0e3e5",
        "on-surface-variant": "#3f4a3e",
        "surface-container": "#eceef0",
        "inverse-on-surface": "#eff1f3",
        "surface-container-low": "#f2f4f6",
        "tertiary-fixed-dim": "#91d78a",
        "background": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#3e4a41",
        "inverse-primary": "#77dc88",
        "tertiary-container": "#357736",
        "secondary-fixed-dim": "#bdcabe",
        "primary-fixed-dim": "#77dc88"
      },
      fontFamily: {
        "body-base": ["Plus Jakarta Sans", "sans-serif"],
        "label-bold": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "body-base": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-bold": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "display-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "display-lg": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }]
      },
      spacing: {
        "sidebar-width": "260px",
        "stack-gap": "1rem",
        "gutter": "1.5rem",
        "container-max-width": "1440px",
        "card-padding": "1.25rem"
      }
    },
  },
  plugins: [PrimeUI],
}

